<?php

/**
 * @file
 * Contains drupalcamp_exemplos.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupalcamp_exemplos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupalcamp_exemplos module.
    case 'help.page.drupalcamp_exemplos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
